name: sample_ui_project
description: A new Flutter project from MOR.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  easy_localization: 3.0.2
  bot_toast: 4.0.3
  pull_to_refresh: 2.0.0
  flutter_bloc: 8.1.2

  shared_preferences: 2.0.17
  equatable: 2.0.5
  dio: 4.0.0
  formz: 0.4.1
  g_json: 4.1.0
  dio_http_cache: 0.3.0
  flutter_svg: 2.0.2
  simple_gradient_text: 1.2.4
  rxdart: 0.27.7
  one_context: 2.1.0
  flutter_keyboard_visibility: 5.4.0
  flutter_countdown_timer: 4.1.0
  pinput: 2.2.31
  cached_network_image: 3.2.3
  webview_flutter: 4.0.6
  flutter_switch: 0.3.2
  image_picker: 0.8.7
  permission_handler: 10.2.0
  units_converter: 2.1.0
  uuid: 3.0.7
  flutter_local_notifications: 13.0.0
  device_info_plus: 8.2.0

  just_audio: 0.9.33

  flutter_spinkit: 5.2.0
  zoom_tap_animation: 1.1.0
  getwidget: 3.1.1

  gap: 3.0.1
  flutter_card_swiper: 7.0.0
  dropdown_button2: 2.3.9

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/fonts/
    - assets/images/
    - assets/translations/

  fonts:
    - family: NotoSansBold
      fonts:
        - asset: assets/fonts/NotoSans-Bold.ttf
    - family: NotoSansExtraBold
      fonts:
        - asset: assets/fonts/NotoSans-ExtraBold.ttf
    - family: NotoSansMedium
      fonts:
        - asset: assets/fonts/NotoSans-Medium.ttf
    - family: NotoSansRegular
      fonts:
        - asset: assets/fonts/NotoSans-Regular.ttf
    - family: NotoSansSemiBold
      fonts:
        - asset: assets/fonts/NotoSans-SemiBold.ttf
